name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main # Atau 'master', sesuaikan dengan branch utamamu

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          # accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }} # Hapus pagar jika kamu simpan Account ID di Secrets juga
          secrets: |
              B2_KEY_ID
              B2_APP_KEY
        env:
          B2_KEY_ID: ${{ secrets.B2_KEY_ID }}
          B2_APP_KEY: ${{ secrets.B2_APP_KEY }}
